### ISSUE TITLE
Python.h missing on 3.9 and 3.10

### ISSUE THREAD

**Issue by mkcms** [actions/setup-python#1006]
**Description:**
A few days ago my builds with Python 3.9 and 3.10 broke due to a missing `Python.h` include in one of the dependent packages that I build during the process. The same setup builds fine for 3.11, 3.12 and 3.13, and it used to work before that for 3.9 and 3.10 as well.

As far as I know, no changes were made to the dependent package.

Example failing job: https://github.com/mkcms/bdx/actions/runs/12715895623/job/35449032864

A successful build from a week ago: https://github.com/mkcms/bdx/actions/runs/12610330973/job/35144803933

**Action version:**
Latest master

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

- 3.9
- 3.10

**Repro steps:**  
Try to compile a C Python extension that uses `Python.h` header.

**Expected behavior:**
No error.

**Actual behavior:**
The `Python.h` header can't be found.

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../python3 -I.. -I/opt/hostedtoolcache/Python/3.10.15/x64/include/python3.10 -fno-strict-aliasing -Wall -Wno-unused -Wno-uninitialized -fvisibility=hidden -fvisibility-inlines-hidden -g -O2 -MT xapian_wrap.lo -MD -MP -MF .deps/xapian_wrap.Tpo -c ../../python3/xapian_wrap.cc  -fPIC -DPIC -o .libs/xapian_wrap.o
../../python3/xapian_wrap.cc:20:10: fatal error: Python.h: No such file or directory
   20 | #include <Python.h>
```

**Comment by priyagupta108** [comment]
Hi @mkcms 👋,
Thank you for your report. We'll investigate the issue and get back to you with the details!

**Comment by priyagupta108** [comment]
Hi @mkcms,
I have attempted to reproduce the issue by forking your repository and running the same setup with Python 3.9 and 3.10. In my case, I did not encounter the `Python.h` missing error.

It's possible that the issue might be caused by cached dependencies or artifacts. Could you try clearing the cache and see if that resolves the problem? 

Additionally, to ensure you are using the latest updates, could you please check with the `actions/setup-python@v5` tag instead of `@master` in your GitHub Actions workflow? 

Please let me know if this helps or if you have any other details that might be relevant.
Thank you.

**Comment by priyagupta108** [comment]
@mkcms 👋,
Just checking in to see if there are any updates on your end regarding this issue? Thank you!

**Comment by priyagupta108** [comment]
@mkcms, just following up to see if there are any updates. Thanks!

**Comment by mkcms** [comment]
Hi @priyagupta108,

The issue no longer reproduces, this can be closed.

Thanks.

**Comment by priyagupta108** [comment]
Hi @mkcms,

Thank you for your update. I am closing this issue as it is no longer reproducible. If you encounter any other issues or need further assistance, please feel free to reach out.

Thanks.
