### ISSUE TITLE
CPython 3.11.0 AttributeError: 'sqlite3.Connection' object has no attribute 'enable_load_extension'

### ISSUE THREAD

**Issue by wangfenjin** [actions/setup-python#540]
Hi @miketimofeev , this issue seems happen again in macOS recently.

You can check the MacOS pipeline  , the[ first attempt](https://github.com/wangfenjin/simple/actions/runs/3307422769/attempts/1) succeed but [second one](https://github.com/wangfenjin/simple/actions/runs/3307422769) failed. No code change.

_Originally posted by @wangfenjin in https://github.com/actions/runner-images/issues/317#issuecomment-1309671885_

**Comment by wangfenjin** [comment]
I check the pipeline again, it works in 3.10.8, break in 3.11.0

**Comment by MaksimZhukov** [comment]
Hello @wangfenjin! Thank you for reporting this!
We will investigate the issue and get back to you as soon as we have updates.

**Comment by IvanZosimov** [comment]
Hi, @wangfenjin 👋 ! Starting from the Python version 3.11.0-beta.1 we decided to use prebuilt universal2 packages for the macOS. As for the versions lower than 3.11.0-beta.1, we used to build packages by hand and [deliberately](https://github.com/actions/runner-images/issues/317#issuecomment-641948840) included support of SQLite load extensions into them. That's why moving from Python 3.10.8 to 3.11.0 caused the problem you stated, and this problem is expected on the Python versions starting from 3.11.0-beta.1. To solve it you may stay on the Python versions below 3.11.0-beta.1 or use workarounds from [this issue](https://github.com/actions/runner-images/issues/317).

If you have any additional questions, feel free to ping us!

**Comment by wangfenjin** [comment]
Understand. Thanks @IvanZosimov

**Comment by franciscojavierarceo** [comment]
@IvanZosimov any update on this? I've actually been encountering this issue.
